apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8sug-chatbot.fullname" . }}-backend
  labels:
    {{- include "k8sug-chatbot.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicaCount }}    
  selector:
    matchLabels:
      app: {{ include "k8sug-chatbot.fullname" . }}-backend
  template:
    metadata:
      labels:
        app: {{ include "k8sug-chatbot.fullname" . }}-backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag | default "latest" }}
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.service.port }}
          env:
            - name: INSTRUCTION
              valueFrom:
                configMapKeyRef:
                  name: chatbot-config
                  key: INSTRUCTION
            - name: KNOWLEDGE
              valueFrom:
                configMapKeyRef:
                  name: chatbot-config
                  key: KNOWLEDGE
            - name: MAX_LENGTH
              valueFrom:
                configMapKeyRef:
                  name: chatbot-config
                  key: MAX_LENGTH
            - name: MIN_LENGTH
              valueFrom:
                configMapKeyRef:
                  name: chatbot-config
                  key: MIN_LENGTH
            - name: TOP_P
              valueFrom:
                configMapKeyRef:
                  name: chatbot-config
                  key: TOP_P
            - name: DO_SAMPLE
              valueFrom:
                configMapKeyRef:
                  name: chatbot-config
                  key: DO_SAMPLE
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.backend.service.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.backend.service.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
