apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8sug-chatbot.fullname" . }}-backend
  labels:
    {{- include "k8sug-chatbot.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}
  selector:
    app: {{ include "k8sug-chatbot.fullname" . }}-backend

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8sug-chatbot.fullname" . }}-frontend
  labels:
    {{- include "k8sug-chatbot.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
  selector:
    app: {{ include "k8sug-chatbot.fullname" . }}-frontend

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8sug-chatbot.fullname" . }}-frontend-lb
  labels:
    {{- include "k8sug-chatbot.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
  selector:
    app: {{ include "k8sug-chatbot.fullname" . }}-frontend
